version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pomme123
    volumes:
      - type: volume
        source: dbtest
        target: /var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 8000:8000
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/vendor
  node:
    build:
      context: .
      dockerfile: Dockerfile.encore.dev
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony/certs
      - type: volume
        target: /app/node_modules
      - type: bind
        source: .
        target: /app
    tty: true

volumes:
  dbtest:
  tls:
